name: Code Lint

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**.cs'
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'

jobs:
  run-linters:
    name: Run source code linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run code linters with auto fix
        uses: wearerequired/lint-action@v2
        with:
          commit_message: "style: code style issues with ${linter}"
          dotnet_format: true
          dotnet_format_dir: src
          dotnet_format_auto_fix: true
          auto_fix: true
          git_name: "C# linter"